BUFF the Extreme Industrial Greenhouse
GTNH-Museum/bartworks-archive pull request #141
Opened 2022-06-20 22:40 UTC by kuba6000

Now you can input fertilizer to get more outputs (up to 400% more)
IC2 +10% per fertilizer per crop per operation
NORMAL +200% per fertilizer per crop per operation

2022-06-21 11:22 UTC, Steelux8 commented
What are the current numbers on this multi, to deserve a buff like this?

2022-06-21 12:18 UTC, kuba6000 commented
@Steelux8 
I just realized that I skipped TWO tiers in the initial calculations... 
Before those changes the machine was ~10 times worse than accelerators.
With those changes it is now the same as accelerators, and with fertilizer 5 times better than accelerators.

2022-06-21 13:28 UTC, miozune commented on src/main/java/com/github/bartimaeusnek/bartworks/common/tileentities/multis/GT_TileEntity_ExtremeIndustrialGreenhouse.java
> +            addInfo("Minimal tier: LUV").
nitpick: `LuV`

2022-06-21 13:36 UTC, kuba6000 commented on src/main/java/com/github/bartimaeusnek/bartworks/common/tileentities/multis/GT_TileEntity_ExtremeIndustrialGreenhouse.java
> +            addInfo("Minimal tier: LUV").
Corrected.

2022-07-03 00:59 UTC, Connor-Colenso requested changes

2022-07-03 00:59 UTC, Connor-Colenso commented on src/main/java/com/github/bartimaeusnek/bartworks/common/tileentities/multis/GT_TileEntity_ExtremeIndustrialGreenhouse.java
> +            addInfo("Minimal tier: " + ChatColorHelper.DARKPURPLE + "EV").
I would prefer usage of the GT_Values colour formatted tier strings instead of colour + LuV being manually written. This is better if we change stuff in future.

2022-07-03 00:59 UTC, Connor-Colenso commented on src/main/java/com/github/bartimaeusnek/bartworks/common/tileentities/multis/GT_TileEntity_ExtremeIndustrialGreenhouse.java
> +            addInfo("Every tier past " + ChatColorHelper.DARKPURPLE + "EV" + ChatColorHelper.GRAY + ", slots are multiplied by 2").
Same

2022-07-03 00:59 UTC, Connor-Colenso commented on src/main/java/com/github/bartimaeusnek/bartworks/common/tileentities/multis/GT_TileEntity_ExtremeIndustrialGreenhouse.java
> +            addInfo("Process time is divided by number of tiers past " + ChatColorHelper.GOLD + "HV" + ChatColorHelper.GRAY + " (Minimum 1 sec)").
Same

2022-07-03 00:59 UTC, Connor-Colenso commented on src/main/java/com/github/bartimaeusnek/bartworks/common/tileentities/multis/GT_TileEntity_ExtremeIndustrialGreenhouse.java
> +            addInfo("Minimal tier: " + ChatColorHelper.LIGHT_PURPLE + "LuV").
Same

2022-07-03 00:59 UTC, Connor-Colenso commented on src/main/java/com/github/bartimaeusnek/bartworks/common/tileentities/multis/GT_TileEntity_ExtremeIndustrialGreenhouse.java
> +            addInfo("Need " + ChatColorHelper.LIGHT_PURPLE + "LuV" + ChatColorHelper.GRAY + " glass tier").
Same

2022-07-03 00:59 UTC, Connor-Colenso commented on src/main/java/com/github/bartimaeusnek/bartworks/common/tileentities/multis/GT_TileEntity_ExtremeIndustrialGreenhouse.java
> +            addInfo("Every tier past " + ChatColorHelper.LIGHT_PURPLE + "LuV" + ChatColorHelper.GRAY + ", slots are multiplied by 4").
Same

2022-07-03 06:05 UTC, kuba6000 commented on src/main/java/com/github/bartimaeusnek/bartworks/common/tileentities/multis/GT_TileEntity_ExtremeIndustrialGreenhouse.java
> +            addInfo("Minimal tier: " + ChatColorHelper.DARKPURPLE + "EV").
Done

2022-07-03 12:44 UTC, Connor-Colenso approved these changes

2022-07-03 12:44 UTC, merged