Enable back piston work and use compacted inputs to check the recipe.
GTNH-Museum/bartworks-archive pull request #169
Opened 2022-07-27 21:28 UTC by kuba6000

2022-07-28 04:13 UTC, miozune approved these changes

2022-07-28 04:18 UTC, Connor-Colenso requested changes
This was accidental on my part. I meant to add a way to toggle this with the screwdriver. Could you quickly add that method override? Should be trivial.

2022-07-28 12:06 UTC, kuba6000 commented
> This was accidental on my part. I meant to add a way to toggle this with the screwdriver. Could you quickly add that method override? Should be trivial.

Why do you want to disable that part ? Did you had any problems with it ? I have no problems with it in my game, works perfectly fine, and doesn't produce much lag.
Toggling the most important part of the multiblock with a screwdriver doesn't make any sense anyway, config value is much better.

Here's a picture of the process. The circle in the middle is an item that is being compressed.

@Connor-Colenso 

![image](https://user-images.githubusercontent.com/53441451/134423076-b0afce00-76b3-4154-bd1e-e4d6a85ec457.png)

2022-07-29 05:59 UTC, Connor-Colenso commented
> > This was accidental on my part. I meant to add a way to toggle this with the screwdriver. Could you quickly add that method override? Should be trivial.
> 
> Why do you want to disable that part ? Did you had any problems with it ? I have no problems with it in my game, works perfectly fine, and doesn't produce much lag. Toggling the most important part of the multiblock with a screwdriver doesn't make any sense anyway, config value is much better.
> 
> @Connor-Colenso
> 
> ![image](https://user-images.githubusercontent.com/53441451/134423076-b0afce00-76b3-4154-bd1e-e4d6a85ec457.png)

I wouldn't really call it the most important part. It's a buggy feature that often breaks during server restarts but a config is better than nothing.

2022-07-29 05:59 UTC, Connor-Colenso approved these changes

2022-07-29 05:59 UTC, merged