Windmill-reblance
GTNH-Museum/bartworks-archive pull request #205
Opened 2022-09-21 14:42 UTC by iouter

For now, the Windmill will

- Speed and output will be affected by wind speed, recipe and rotor
- Macerates 16 items at a time
- Roughly equivalent to 2~12 steam macerators (full speed, and depending on the rotor)
- High wind speeds will decrease output
- Will be replaced by the Steam Grinder

2022-09-21 18:24 UTC, Glease requested changes

2022-09-21 18:24 UTC, Glease commented on src/main/java/com/github/bartimaeusnek/bartworks/common/items/BW_Stonage_Rotors.java
> +    public float getmRotor() {
probably should be `getRotor`. it's probably a good idea to rename this property in general. What about `OutputMultiplier`?

2022-09-21 18:24 UTC, Glease commented on src/main/java/com/github/bartimaeusnek/bartworks/common/tileentities/multis/GT_TileEntity_Windmill.java
> +        } catch (java.lang.NullPointerException e){
why fully qualify the name of exception? especially when it's in java.lang

2022-09-21 18:24 UTC, Glease commented on src/main/java/com/github/bartimaeusnek/bartworks/common/tileentities/multis/GT_TileEntity_Windmill.java
> +    private float[] multiplierRecipe(ItemStack itemStack) {
please at least leave a comment saying what is the meaning of the return value. Preferably use a dedicated class for this.

2022-09-21 18:24 UTC, Glease commented on src/main/java/com/github/bartimaeusnek/bartworks/common/loaders/ItemRegistry.java
> +            1000000,
This will not work. Durability max is Short.MAX_VALUE, which is 32767.

2022-09-22 00:18 UTC, iouter commented on src/main/java/com/github/bartimaeusnek/bartworks/common/loaders/ItemRegistry.java
> +            1000000,
![)%B42H$Z2(8 PI HU IG2Z0](https://user-images.githubusercontent.com/62897714/191631949-af3d6962-d1d2-45f1-992a-4ddf26c94537.png)
it works fine.

2022-09-22 00:20 UTC, iouter commented on src/main/java/com/github/bartimaeusnek/bartworks/common/tileentities/multis/GT_TileEntity_Windmill.java
> +    private float[] multiplierRecipe(ItemStack itemStack) {
will return max and min value of the multiplier, the average of these is used to calculate the multiplier.

2022-09-22 02:11 UTC, Glease commented on src/main/java/com/github/bartimaeusnek/bartworks/common/loaders/ItemRegistry.java
> +            1000000,
Try reload the world.

2022-09-23 12:20 UTC, iouter commented
@Glease

2022-09-23 13:45 UTC, Glease approved these changes
should be good now.

2022-09-23 15:27 UTC, merged