Add batch mode to MEBF, MVF and MCR
GTNH-Museum/bartworks-archive pull request #220
Opened 2022-10-16 15:52 UTC by S4mpsa

Same as PAs: Toggle with Sneak+Wire Cutter on the controller. https://github.com/GTNewHorizons/GT5-Unofficial/pull/1446

Increases parallel by up to 128 times (32 768 maximum), while making recipes take up to 128 times longer at the same ratio. This also allows circumventing the 1-tick limit of machines, but is primarily meant for lag reduction.

2022-10-17 01:49 UTC, Connor-Colenso commented
I mean, this is in essence a huge buff for these machines, no?

2022-10-17 06:14 UTC, S4mpsa commented
If you consider the 1-tick limit a balance measure, then sure.

It's mostly a buff to MCRs doing low level recipes, and you quickly run into input problems with fluid recipes.

I wouldn't call it a "huge" buff, but I can add a clamp so the processing time doesn't go below 128 ticks in batch mode.

2022-10-17 06:24 UTC, minecraft7771 requested changes, later dismissed

2022-10-17 06:24 UTC, minecraft7771 commented on src/main/java/com/github/bartimaeusnek/bartworks/common/tileentities/multis/mega/GT_TileEntity_MegaChemicalReactor.java
> +        return true;
If you do nothing when not sneaking you should return false or maybe even call super but for now the super wouldn't do anything.

2022-10-17 06:24 UTC, minecraft7771 commented on src/main/java/com/github/bartimaeusnek/bartworks/common/tileentities/multis/mega/GT_TileEntity_MegaVacuumFreezer.java
> +        return true;
same

2022-10-17 06:24 UTC, minecraft7771 commented on src/main/java/com/github/bartimaeusnek/bartworks/common/tileentities/multis/mega/GT_TileEntity_MegaBlastFurnace.java
> +                GT_Utility.sendChatToPlayer(aPlayer, "Batch recipes");
I know GT as a whole is very inconsistent with this but would be cool if you'd put the strings into the lang file

2022-10-22 19:33 UTC, closed without merging

2022-10-22 23:59 UTC, Dream-Master commented
@S4mpsa why you close it ?

2022-10-22 23:59 UTC, Dream-Master commented
nevermind found new pr