EIG: Fix stocking input bus exploit
GTNH-Museum/bartworks-archive pull request #230
Opened 2022-10-31 15:56 UTC by kuba6000

Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11768

2022-10-31 16:04 UTC, minecraft7771 requested changes

2022-10-31 16:04 UTC, minecraft7771 commented on src/main/java/com/github/bartimaeusnek/bartworks/common/tileentities/multis/GT_TileEntity_ExtremeIndustrialGreenhouse.java
> +            int toUse = Math.min(64, input.stackSize);
Wouldn't it be cleaner to use `input.getMaxStackSize()` instead of hard coded 64?

2022-10-31 16:04 UTC, minecraft7771 commented on src/main/java/com/github/bartimaeusnek/bartworks/common/tileentities/multis/GT_TileEntity_ExtremeIndustrialGreenhouse.java
> +                if (g.input.stackSize < 64 && GT_Utility.areStacksEqual(g.input, input)) {
We should also use the max stack size getter here too imo.

2022-10-31 16:04 UTC, kuba6000 commented on src/main/java/com/github/bartimaeusnek/bartworks/common/tileentities/multis/GT_TileEntity_ExtremeIndustrialGreenhouse.java
> +            int toUse = Math.min(64, input.stackSize);
No, the slots in multi holds 64

2022-10-31 16:06 UTC, kuba6000 commented on src/main/java/com/github/bartimaeusnek/bartworks/common/tileentities/multis/GT_TileEntity_ExtremeIndustrialGreenhouse.java
> +            int toUse = Math.min(64, input.stackSize);
So they will be added in the next iteration to the same slot anyway

2022-10-31 16:07 UTC, minecraft7771 commented on src/main/java/com/github/bartimaeusnek/bartworks/common/tileentities/multis/GT_TileEntity_ExtremeIndustrialGreenhouse.java
> +            int toUse = Math.min(64, input.stackSize);
I see

2022-10-31 16:07 UTC, minecraft7771 approved these changes

2022-10-31 16:09 UTC, merged

2022-11-05 18:09 UTC, xSkewer commented
Getting an already tesselating crash with the rendering changes on existing EIGs. Have not tested newly placed EIGs.

2022-11-05 18:11 UTC, kuba6000 commented
> Getting an already tesselating crash with the rendering changes on existing EIGs. Have not tested newly placed EIGs.

Will fix