adjusted the balance of the EIG
GTNH-Museum/bartworks-archive pull request #296
Opened 2023-03-03 21:55 UTC by bruce-webb

* Added more details to the tooltip to be more clear on what fertilizer & CO2 does

* Change the starting slots of IC2 mode to 8. mostly to match the plots in the EIG

* Change the usage of fertilizer to match what the tooltip say per operation

* Change the calculation of the multiplyer for IC2 mode to be bonus to growth time

* Added a way to boost growing speed in IC2 mode by adding CO2 gas match to the number of crop slots

* Added a way to boost the production in normal mode with CO2 gas

2023-03-03 22:25 UTC, chochem commented
we have a feature freeze until stable is done

2023-03-03 22:27 UTC, Dream-Master commented
All fine we just not merge it

2023-03-04 10:05 UTC, kuba6000 requested changes

2023-03-04 10:05 UTC, kuba6000 commented on src/main/java/com/github/bartimaeusnek/bartworks/common/tileentities/multis/GT_TileEntity_ExtremeIndustrialGreenhouse.java
> -                .addInfo("1 Fertilizer per 1 crop +10%").addInfo(BW_Tooltip_Reference.TT_BLUEPRINT).addSeparator()
That info was right (1/40)*4 = 0.1

2023-03-04 10:05 UTC, kuba6000 commented on src/main/java/com/github/bartimaeusnek/bartworks/common/tileentities/multis/GT_TileEntity_ExtremeIndustrialGreenhouse.java
> -                .addInfo("1 Fertilizer per 1 crop +200%")
That info was right (1/2)*4 = 2

2023-03-04 10:05 UTC, kuba6000 commented on src/main/java/com/github/bartimaeusnek/bartworks/common/tileentities/multis/GT_TileEntity_ExtremeIndustrialGreenhouse.java
> +        for (GreenHouseSlot s : mStorage) maxboost += s.input.stackSize * 2;
Why are you breaking the fertilizer implementation. Thats here to take 40 fertilizer per operation per crop in IC2 mode instead of 2

2023-03-04 10:05 UTC, kuba6000 commented on src/main/java/com/github/bartimaeusnek/bartworks/common/tileentities/multis/GT_TileEntity_ExtremeIndustrialGreenhouse.java
> +            multiplier += co2NeedsMet ? 1d : 0d;
Why removing the multiplier? You can just do multiplier += co2boost

2023-03-04 10:05 UTC, kuba6000 commented on src/main/java/com/github/bartimaeusnek/bartworks/common/tileentities/multis/GT_TileEntity_ExtremeIndustrialGreenhouse.java
> +        boolean co2NeedsMet = this.depleteInput(new FluidStack(carbonDioxide, carbonDioxideUsage));
Bad implementation. It should support fractions of full speed like fertilizer does.

2023-03-04 10:05 UTC, kuba6000 commented on src/main/java/com/github/bartimaeusnek/bartworks/common/tileentities/multis/GT_TileEntity_ExtremeIndustrialGreenhouse.java
> +        else if (isIC2Mode) mMaxSlots = 8 << (2 * (tier - 6));
Slots were balanced around accelerators (IV Accelerator (32x) can accelerate 6 blocks for 6 amps of IV, we are accelerating 4 crops for 4 apms (1 AMP LuV)), now you are buffing it to be 2x better than accelerators

2023-03-04 10:05 UTC, kuba6000 commented on src/main/java/com/github/bartimaeusnek/bartworks/common/tileentities/multis/GT_TileEntity_ExtremeIndustrialGreenhouse.java
> +    private int carbonDioxideUsage = 0;
The variable can be local, we dont need to use it anywhere else.

2023-03-04 17:57 UTC, bruce-webb commented on src/main/java/com/github/bartimaeusnek/bartworks/common/tileentities/multis/GT_TileEntity_ExtremeIndustrialGreenhouse.java
> +        boolean co2NeedsMet = this.depleteInput(new FluidStack(carbonDioxide, carbonDioxideUsage));
Alright I copied the weedex fluid drain. I can change it to be more dynamic.

2023-03-05 03:17 UTC, bruce-webb commented on src/main/java/com/github/bartimaeusnek/bartworks/common/tileentities/multis/GT_TileEntity_ExtremeIndustrialGreenhouse.java
> +        for (GreenHouseSlot s : mStorage) maxboost += s.input.stackSize * 2;
The formula is much the same as you can see below. Instead of it being burst production its flatten out. The  bonus can be adjusted. 

![image](https://user-images.githubusercontent.com/39678316/222939225-7b91f732-e64a-4fdd-a80d-686458672616.png)

2023-03-05 03:50 UTC, bruce-webb commented on src/main/java/com/github/bartimaeusnek/bartworks/common/tileentities/multis/GT_TileEntity_ExtremeIndustrialGreenhouse.java
> +        else if (isIC2Mode) mMaxSlots = 8 << (2 * (tier - 6));
I don't see that as a bad thing since its a multi block for growing crops only. It can't be used for cross breeding so its a specialized machine for crop growth. Which why I think it makes sense. 

To be honest this multi block is the most underwhelming IV multi block with 2 IV energy inputs. A EV accelerator and a IV crop manager is a much better investment IMO and cheaper since it doesn't cost 4 IV accelerators. The crop manager can give a area of 27 by 27 with 25% bonus chance output (next pr for the EIG) and it uses pennies for fertilizer as well as power, shoot or even the forestry multi.

2023-03-05 03:54 UTC, bruce-webb commented on src/main/java/com/github/bartimaeusnek/bartworks/common/tileentities/multis/GT_TileEntity_ExtremeIndustrialGreenhouse.java
> +        for (GreenHouseSlot s : mStorage) maxboost += s.input.stackSize * 2;
Its also clear in the description on what is happening since that magic number of 40 is never used anywhere in the description.

2023-03-05 07:32 UTC, kuba6000 commented on src/main/java/com/github/bartimaeusnek/bartworks/common/tileentities/multis/GT_TileEntity_ExtremeIndustrialGreenhouse.java
> +        for (GreenHouseSlot s : mStorage) maxboost += s.input.stackSize * 2;
I dont think you understood what the description is saying and also didnt read my quest in QB at all where i described how it works using examples with tea crops ❤️‍🔥.
That variable controls how much fertilizer is needed for 400% boost.
Description says "You can insert fertilizer each operation to get more drops (max +400%)" and in IC2 section "1 Fertilizer per 1 crop +10%"
Quick maths and you get the number 40: 400/10 = 40 meaning that you need 40 fertilizer per crop per operation.
With your change the max boost in IC2 mode becomes 20% because it can't take more than 2 fertilizer

2023-03-05 07:39 UTC, kuba6000 commented on src/main/java/com/github/bartimaeusnek/bartworks/common/tileentities/multis/GT_TileEntity_ExtremeIndustrialGreenhouse.java
> -        if (watercheck > 0 && !debug) return false;
Debug variable vanished?

2023-03-06 05:38 UTC, bruce-webb commented on src/main/java/com/github/bartimaeusnek/bartworks/common/tileentities/multis/GT_TileEntity_ExtremeIndustrialGreenhouse.java
> +        for (GreenHouseSlot s : mStorage) maxboost += s.input.stackSize * 2;
I see, didn't read the quest book in its entirety. But its still very much misleading since it states that fertilizer is used for bonus drops in IC2 mode.

2023-03-08 16:41 UTC, kuba6000 requested changes

2023-03-08 16:41 UTC, kuba6000 commented on src/main/java/com/github/bartimaeusnek/bartworks/common/tileentities/multis/GT_TileEntity_ExtremeIndustrialGreenhouse.java
> +        else if (isIC2Mode) mMaxSlots = 8 << (tier - 6);
Why are you trying to do such a massive and unreasonable nerf? Thats a 97% nerf at UMV voltage (32 times worse !) and also it makes weed-ex mechanic completely useless

2023-03-15 21:56 UTC, kuba6000 requested changes
Ok let me get this straight:
1. We are back at 100% buff
2. + [Plus] You need to replicate much less crops now!
3. My point of balance around IV accelerator is completely gone now
4. Weed-ex still useless
5. All currently built EIG's will stop working after the update and people will be left with huge amount of crops

Why are you even trying to give it more crops at low tier? It is supposed to start poorly and gets very insane at higher tiers (thats how perfect overclocking is supposed to work). If that change is only because there is 8 visible crops inside then please revert everything except CO2 boost, the animation is not something you should balance a multi around, its literally just 8 blocks of wheat inside.
And if there is a real reason then please explain why these changes are needed because they don't look like they are.

2023-03-16 03:41 UTC, closed without merging