migrate recipes to RA2
GTNH-Museum/bartworks-archive pull request #349
Opened 2023-08-03 10:36 UTC by boubou19

2023-09-04 16:08 UTC, chochem requested changes
only looked at the code, did not try ingame.
Mostly some big issue with centrifuge recipes.
If you dont want to fix the chem balance stuff, thats fine. at least maybe add a todo comment there.

2023-09-04 16:08 UTC, chochem commented on src/main/java/com/github/bartimaeusnek/bartworks/API/BioObjectAdder.java
> +                        .eut(2).addTo(sCentrifugeRecipes);
duration and eut seem to be wrong

2023-09-04 16:08 UTC, chochem commented on src/main/java/com/github/bartimaeusnek/bartworks/common/loaders/FluidLoader.java
> +                        .fluidInputs(new FluidStack(B.getFluid(), 1000)).fluidOutputs(dnaFluid).duration(15 * SECONDS)
again, time and eut are wrong.

2023-09-04 16:08 UTC, chochem commented on src/main/java/com/github/bartimaeusnek/bartworks/common/loaders/recipes/Electrolyzer.java
> +                        GT_OreDictUnificator.get(OrePrefixes.dust, Materials.SiliconDioxide, 1L))
chem balance is wrong here and in all the following. needs to be GT_OreDictUnificator.get(OrePrefixes.dust, Materials.SiliconDioxide, 3L) here, and 3x sio2 in the other recipes as well

2023-09-04 16:08 UTC, chochem commented on src/main/java/com/github/bartimaeusnek/bartworks/common/loaders/recipes/Electrolyzer.java
> +                .itemOutputs(
for this one chembalance is messed up far worse. but it starts with the very weird compound formula and should be adjusted there first

2023-09-04 16:08 UTC, chochem commented on src/main/java/com/github/bartimaeusnek/bartworks/common/loaders/recipes/Electrolyzer.java
> +                .itemOutputs(
same here. no chembalance, very strange chem formula.

2023-09-04 16:08 UTC, chochem commented on src/main/java/com/github/bartimaeusnek/bartworks/common/loaders/recipes/Electrolyzer.java
> +                .itemOutputs(
same here. no chembalance, very strange chem formula.

2023-09-04 16:08 UTC, chochem commented on src/main/java/com/github/bartimaeusnek/bartworks/common/loaders/recipes/Electrolyzer.java
> +                .itemOutputs(
same here. no chembalance, very strange chem formula.

2023-09-04 16:08 UTC, chochem commented on src/main/java/com/github/bartimaeusnek/bartworks/system/material/processingLoaders/AddSomeRecipes.java
> +                .fluidOutputs(WerkstoffLoader.Xenon.getFluidOrGas(1)).duration(15 * SECONDS).eut(2)
time and eut wrong

2023-09-04 16:08 UTC, chochem commented on src/main/java/com/github/bartimaeusnek/bartworks/system/material/processingLoaders/AddSomeRecipes.java
> +                .fluidOutputs(WerkstoffLoader.Xenon.getFluidOrGas(2)).duration(15 * SECONDS).eut(2)
time and eut wrong

2023-09-04 16:08 UTC, chochem commented on src/main/java/com/github/bartimaeusnek/bartworks/system/material/processingLoaders/AddSomeRecipes.java
> +                .fluidOutputs(WerkstoffLoader.Xenon.getFluidOrGas(4)).duration(15 * SECONDS).eut(2)
time and eut wrong

2023-09-04 16:08 UTC, chochem commented on src/main/java/com/github/bartimaeusnek/bartworks/system/material/processingLoaders/AddSomeRecipes.java
> +                .duration(15 * SECONDS).eut(2).addTo(sCentrifugeRecipes);
time and eut wrong

2023-09-04 16:08 UTC, chochem commented on src/main/java/com/github/bartimaeusnek/bartworks/common/loaders/recipes/Centrifuge.java
> +                .addTo(sCentrifugeRecipes);
time and eut wrong

2023-09-04 16:08 UTC, chochem commented on src/main/java/com/github/bartimaeusnek/bartworks/common/loaders/recipes/Centrifuge.java
> +                .duration(15 * SECONDS).eut(2).addTo(sCentrifugeRecipes);
time and eut wrong

2023-09-04 16:08 UTC, chochem commented on src/main/java/com/github/bartimaeusnek/bartworks/common/loaders/recipes/Centrifuge.java
> +                    .duration(15 * SECONDS).eut(2).addTo(sCentrifugeRecipes);
time and eut wrong

2023-09-04 16:08 UTC, chochem commented on src/main/java/com/github/bartimaeusnek/bartworks/common/loaders/recipes/Centrifuge.java
> +                .addTo(sCentrifugeRecipes);
time and eut wrong

2023-09-04 16:08 UTC, chochem commented on src/main/java/com/github/bartimaeusnek/bartworks/common/loaders/recipes/Centrifuge.java
> +                .addTo(sCentrifugeRecipes);
time and eut wrong

2023-09-04 16:08 UTC, chochem commented on src/main/java/com/github/bartimaeusnek/bartworks/common/loaders/recipes/Centrifuge.java
> +                .addTo(sCentrifugeRecipes);
time and eut wrong

2023-09-04 16:08 UTC, chochem commented on src/main/java/com/github/bartimaeusnek/bartworks/system/material/GT_Enhancement/PlatinumSludgeOverHaul.java
> +                .duration(15 * SECONDS).eut(2).addTo(sCentrifugeRecipes);
time and eut wrong

2023-09-04 16:08 UTC, chochem commented on src/main/java/com/github/bartimaeusnek/bartworks/system/material/processingLoaders/AdditionalRecipes.java
> +                .fluidOutputs(Materials.Water.getFluid(8832)).duration(15 * SECONDS).eut(2).addTo(sCentrifugeRecipes);
time and eut wrong

2023-09-04 16:08 UTC, chochem commented on src/main/java/com/github/bartimaeusnek/bartworks/system/material/werkstoff_loaders/recipe/CrushedLoader.java
> +                .noFluidInputs().noFluidOutputs().duration(15 * SECONDS).eut(2).addTo(sCentrifugeRecipes);
time and eut wrong

2023-09-04 16:08 UTC, chochem commented on src/main/java/com/github/bartimaeusnek/bartworks/system/material/werkstoff_loaders/recipe/CrushedLoader.java
> +                .noFluidInputs().noFluidOutputs().duration(15 * SECONDS).eut(2).addTo(sCentrifugeRecipes);
time and eut wrong

2023-09-04 16:46 UTC, chochem commented on src/main/java/com/github/bartimaeusnek/bartworks/system/material/werkstoff_loaders/recipe/BlockLoader.java
> +                    .eut(TierEU.RECIPE_LV).addTo(sCutterRecipes);
should be variants with 3 different fluids (and times) and nothing without fluids. probably applies to all cutter recipes in this PR

2023-09-04 17:03 UTC, chochem commented on src/main/java/com/github/bartimaeusnek/bartworks/system/material/werkstoff_loaders/recipe/BlockLoader.java
> +                    .eut(TierEU.RECIPE_LV).addTo(sCutterRecipes);
should hopefully be resolved by https://github.com/GTNewHorizons/GT5-Unofficial/pull/2271

2023-09-04 22:58 UTC, chochem commented on src/main/java/com/github/bartimaeusnek/bartworks/system/material/werkstoff_loaders/recipe/BlockLoader.java
> +                    .eut(TierEU.RECIPE_LV).addTo(sCutterRecipes);
though a GT dep update would be needed for it to work in dev env

2023-09-05 18:25 UTC, boubou19 commented
@chochem i'm not doing chem rebalance in this PR, main goal is to have 1:1 recipes with RA1, so i think i have adressed all your concerns

2023-09-05 18:35 UTC, chochem commented on src/main/java/com/github/bartimaeusnek/bartworks/system/material/GT_Enhancement/PlatinumSludgeOverHaul.java
> +            .itemInputs(GT_Utility.getIntegratedCircuit(11))
best to keep the circuit the same, or is there a reason not to?

2023-09-05 18:38 UTC, boubou19 commented on src/main/java/com/github/bartimaeusnek/bartworks/system/material/GT_Enhancement/PlatinumSludgeOverHaul.java
> +            .itemInputs(GT_Utility.getIntegratedCircuit(11))
likely a typo

2023-09-05 18:41 UTC, chochem approved these changes

2023-09-06 19:14 UTC, merged