unbreak cracker structure
GTNH-Museum/bartworks-archive pull request #4
Opened 2021-02-07 21:10 UTC by botn365

make new cracker not break already existing structures (mostly some of the controllers will need to be mirrord)

2021-02-07 21:33 UTC, bartimaeusnek requested changes
This allows for infinite Wallsharing, effectively reducing the cost per multi to less than ~70% if stacked.

2021-03-14 23:49 UTC, mitchej123 approved these changes

2021-05-07 06:21 UTC, Glease commented
@Dream-Master let's merge this before 2.1.1.0 happens.

2021-05-07 06:37 UTC, Dream-Master commented
i am not agaist it until we have a better idea but its barts mod

2021-05-16 11:24 UTC, Dream-Master commented
@bartimaeusnek any better idea or is this a duct tape fix i can pull ?

2021-05-19 17:48 UTC, Dream-Master commented
@bartimaeusnek i am open for a better fix/change if you can code some. In the mean time i will merge this otherwise we get more complains if people need to rebuild whole setups after a update from 2.1.0.0 to 2.1.1.0.

2021-05-19 17:48 UTC, merged