add MegaChemicalReactor
GTNH-Museum/bartworks-archive pull request #86
Opened 2022-02-04 07:16 UTC by SKYCATV587

2022-02-04 17:51 UTC, draknyte1 reviewed
I think we should either nerf the LCR if this is added with the ability to be properly tiered or just discourage further use in general.

2022-02-04 20:52 UTC, Steelux8 commented
From the screenshot, it looks like a pretty small multi to be a mega. On the other hand, avoiding those abominations that never fit in any build is also something I'd like.

2022-02-04 21:06 UTC, bombcar commented
Perhaps rename it the Very Large Chemical Reactor and make it a bit bigger heh, instead of a 3x3 glass face 5x5?

2022-02-05 03:25 UTC, SKYCATV587 commented
> Perhaps rename it the Very Large Chemical Reactor and make it a bit bigger heh, instead of a 3x3 glass face 5x5?

Because mcr is different from other mega machines, it will be used more, so I don't design it very large

2022-02-06 16:03 UTC, Glease requested changes
Balance aside, there is a lot of minor issues with code. Much of the review comments in mega LCR also applies to the mega cracker, but I got lazy..😛

2022-02-06 16:03 UTC, Glease commented on src/main/java/com/github/bartimaeusnek/bartworks/common/loaders/ItemRegistry.java
> +            ItemRegistry.megaMachines[3] = new GT_TileEntity_MegaChemicalReactor(13111, "MegaChemicalReactor", "Mega Chemical Reactor").getStackForm(1L);
Where did you get these IDs from? Put it in bartworks' space.

2022-02-06 16:03 UTC, Glease commented on src/main/java/com/github/bartimaeusnek/bartworks/common/tileentities/multis/mega/GT_TileEntity_MegaChemicalReactor.java
> +        tt.addMachineType("Molecular Surgery Machine")
Don't get too creative at machine type. It makes searching in NEI harder than it should be. Let's keep it the same as the non mega version.

2022-02-06 16:03 UTC, Glease commented on src/main/java/com/github/bartimaeusnek/bartworks/common/tileentities/multis/mega/GT_TileEntity_MegaChemicalReactor.java
> +                .addEnergyHatch("Hint block with dot 3")
Use `.addXXX("Location of hatch, Descriptive or not", 3)` instead.

For energy hatches specifically, should also notice the energy hatch tier cannot exceed glass tier.

2022-02-06 16:03 UTC, Glease commented on src/main/java/com/github/bartimaeusnek/bartworks/common/tileentities/multis/mega/GT_TileEntity_MegaChemicalReactor.java
> +                .addStructureHint("This Mega Multiblock is too big to have its structure hologram displayed fully.")
Remove this line. 225 blocks is well below the limit.

2022-02-06 16:03 UTC, Glease commented on src/main/java/com/github/bartimaeusnek/bartworks/common/tileentities/multis/mega/GT_TileEntity_MegaChemicalReactor.java
> +        if (this.glasTier != 8 && !this.mEnergyHatches.isEmpty()) {
You will probably want this if block to happen after checkPiece().

2022-02-06 16:03 UTC, Glease commented on src/main/java/com/github/bartimaeusnek/bartworks/common/tileentities/multis/mega/GT_TileEntity_MegaChemicalReactor.java
> +    public String[] getStructureDescription(ItemStack itemStack){
If you used addXXX in createTooltip properly you don't need to override this.

2022-02-06 16:03 UTC, Glease commented on src/main/java/com/github/bartimaeusnek/bartworks/common/tileentities/multis/mega/GT_TileEntity_MegaChemicalReactor.java
> +    private int mCoilAmount;
mCoilAmount is completely unused. Remove it.

2022-02-06 16:03 UTC, Glease commented on src/main/java/com/github/bartimaeusnek/bartworks/common/tileentities/multis/mega/GT_TileEntity_MegaChemicalReactor.java
> +                    onElementPass(GT_TileEntity_MegaChemicalReactor::onCoilAdded, ofBlock(GregTech_API.sBlockCasings4, 7))
mCoilAmount is completely unused. Remove it.

2022-02-06 16:03 UTC, Glease commented on src/main/java/com/github/bartimaeusnek/bartworks/common/tileentities/multis/mega/GT_TileEntity_MegaChemicalReactor.java
> +    private void onCasingAdded() {
mCoilAmount is completely unused. Remove it.

2022-02-06 16:03 UTC, Glease commented on src/main/java/com/github/bartimaeusnek/bartworks/common/tileentities/multis/mega/GT_TileEntity_MegaOilCracker.java
> +                .addEnergyHatch("Hint block with dot 3")
Same as the other mult here.

2022-02-06 16:03 UTC, Glease commented on src/main/java/com/github/bartimaeusnek/bartworks/common/tileentities/multis/mega/GT_TileEntity_MegaOilCracker.java
> +        if (this.glasTier != 8 && !this.mEnergyHatches.isEmpty()) {
Same here.

2022-02-06 16:03 UTC, Glease commented on src/main/java/com/github/bartimaeusnek/bartworks/common/tileentities/multis/mega/GT_TileEntity_MegaOilCracker.java
> +//import com.sun.istack.internal.NotNull;
Remove commented out imports.

2022-02-06 16:03 UTC, Glease commented on src/main/java/com/github/bartimaeusnek/bartworks/common/tileentities/multis/mega/GT_TileEntity_MegaOilCracker.java
> +    public HeatingCoilLevel getCoilLevel() {
You don't need to override this. Just use `this.getCoilLever()` wherever super class uses `this.heatLevel`

2022-02-06 19:23 UTC, Dream-Master commented
@SKYCATV587

2022-02-07 12:17 UTC, Steelux8 commented
Is the mega LCR size fine? What's the size of it now? It seems quite smaller than the other megas, including this new oil cracker. With how overpowered the LCR is, I'm not sure about this.

2022-02-07 15:09 UTC, SKYCATV587 commented
> 

Yes ,Because mcr is different from other mega machines, it will be used more, so I don't design it very large,I only let it be more expensive than other MEGA Machine,it need 7 fusion coils.

2022-02-07 23:22 UTC, Glease approved these changes
Code wise it now looks ok. Not sure about balance though.

2022-02-08 10:37 UTC, Steelux8 commented
Balance can be changed later, and it heavily depends on whether or not the LCR will get rebalanced as well.

2022-02-08 18:11 UTC, Dream-Master commented
> Balance can be changed later, and it heavily depends on whether or not the LCR will get rebalanced as well.

No balance need to be done first.

2022-02-09 11:41 UTC, merged

2022-02-26 11:23 UTC, Pxx500 commented
![image](https://user-images.githubusercontent.com/81298696/155841303-be42aaea-f032-4b83-8507-b0615a8ed712.png)
Quality design, do you even test before implementing?

2022-02-26 11:30 UTC, Pxx500 commented
![image](https://user-images.githubusercontent.com/81298696/155841479-a2382e07-2974-4e8d-ae87-822148d09b84.png)
Same here, good design

2022-02-26 12:38 UTC, SKYCATV587 commented
> ![image](https://user-images.githubusercontent.com/81298696/155841479-a2382e07-2974-4e8d-ae87-822148d09b84.png) Same here, good design

MBF and MDT have the same bug,i dont know how to deal with it

2022-02-26 13:35 UTC, kuba6000 commented
> > ![image](https://user-images.githubusercontent.com/81298696/155841479-a2382e07-2974-4e8d-ae87-822148d09b84.png) Same here, good design
> 
> MBF and MDT have the same bug,i dont know how to deal with it

I fixed it already here: https://github.com/GTNewHorizons/bartworks/pull/97
The MBF and MDT works normally.

2022-02-26 17:12 UTC, SKYCATV587 commented
> > > ![image](https://user-images.githubusercontent.com/81298696/155841479-a2382e07-2974-4e8d-ae87-822148d09b84.png) Same here, good design
> > 
> > 
> > MBF and MDT have the same bug,i dont know how to deal with it
> 
> I fixed it already here: #97 The MBF and MDT works normally.
oh, thanks， i saw it .I just thought it was another bug before I said mbf and mdt had